<?php

namespace Xtending\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Proceso
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntidadesRepository extends EntityRepository
{
    public function findByFiltrosPlanificacion($empresasIds, $paisesIds, $nombre, $ciudad, $estado, $pais)
    {
        if (count($empresasIds))
        {
	    	$q = $this->createQueryBuilder('e');
	    	if ($nombre != '') { 
			$q->add('where', 'e.nombre LIKE :nombre')
			->setParameter('nombre', '%'.$nombre.'%');
	    	}
	    	if ($ciudad != '') {
			$q->andWhere('e.ciudad LIKE :ciudad')
			->setParameter('ciudad', '%'.$ciudad.'%');
	    	}
	    	if ($estado != '') {
			$q->andWhere('e.estado LIKE :estado')
			->setParameter('estado', '%'.$estado.'%');
	    	}
	    	
			//Clientes/Proveedores segun corresponda
			$q->andWhere('e.id IN (:empresas)')
			->setParameter('empresas', $empresasIds->toArray());
	// 		$q->andWhere('e.pais IN (:paisIds)')
	// 		->setParameter('pasiIds', $paisesIds);
			
			//Paises del Form
			if (count($pais)){
				$q->andWhere('e.pais IN (:pais)')
				->setParameter('pais', $pais->toArray());
			}
			$resultado = $q->getQuery()->getResult();
		
        } else {
        	$resultado = new ArrayCollection();
        }
		return $resultado;
    }
}
