<?php

namespace Xtending\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Proceso
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductosRepository extends EntityRepository
{
    public function findByFiltrosPlanificacion($empresasIds, $nombre, $entidad)
    {
    	$q = $this->createQueryBuilder('e');
    	if ($nombre != '')
    	{
    	$q->add('where', 'e.nombre LIKE :nombre')
    	->setParameter('nombre', '%'.$nombre.'%');
    	}
    	//Dentro de su listado de empresas
    	$q->andWhere('e.entidad IN (:empresas)')
    	->setParameter('empresas', $empresasIds->toArray());
    	
    	if (count($entidad)){
			$q->andWhere('e.entidad IN (:entidad)')
			->setParameter('entidad', $entidad->toArray());
		}	
        
        return $q->getQuery()->getResult();
    }
}
