<?php

namespace Xtending\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Proceso
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsableEmpresaRepository extends EntityRepository
{
    public function findResponsableEmpresa($empresaUser, $empresa)
    {
    	$q = $this->createQueryBuilder('e');
    	$q->select('c.email')->innerJoin('e.contacto', 'c');
		
    	//El usuario tiene que tener asignada mi empresa
		$q->add('where', 'e.contactoAsignadoEmpresa = :empresaUser')
		->setParameter('empresaUser', $empresaUser);
    	//El usuario debe ser de la empresa en vista
    	$q->andWhere('e.contactoEmpresa = :empresa')
		->setParameter('empresa', $empresa);
    	
		$resultado = $q->getQuery()->getResult();
    
        return $resultado;
    }
}
