<?php

namespace Xtending\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Proceso
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SitesRepository extends EntityRepository
{
    public function findByFiltrosPlanificacion($empresasIds, $paisesIds, $nombre, $ciudad, $estado, $pais, $entidad)
    {
    	
    		
	    	$q = $this->createQueryBuilder('e');
	    	if ($nombre != '') {
	    	$q->add('where', 'e.nombre LIKE :nombre')
	    	->setParameter('nombre', '%'.$nombre.'%');
	    	}
	    	if ($ciudad != ''){
	    	$q->andWhere('e.ciudad LIKE :ciudad')
	    	->setParameter('ciudad', '%'.$ciudad.'%');
	    	}
	    	if ($estado != ''){
	    	$q->andWhere('e.estado LIKE :estado')
	    	->setParameter('estado', '%'.$estado.'%');
	    	}
	    	//Dentro de su listado de empresas
	    	$q->andWhere('e.entidad IN (:empresas)')
	    	->setParameter('empresas', $empresasIds->toArray());
	    	
	    	if (count($pais)){
	    		$q->andWhere('e.pais IN (:pais)')
	    		->setParameter('pais', $pais->toArray());
	    	}
			if (count($entidad)){
				$q->andWhere('e.entidad IN (:entidad)')
				->setParameter('entidad', $entidad->toArray());
			}
        
        	$resultado = $q->getQuery()->getResult();
        
        return $resultado;
    }
}
