Amateur\ObjectBundle\Entity\Category:
    type: entity
    table: category
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 300
            fixed: false
            nullable: true
        code:
            type: string
            length: 20
            fixed: false
            nullable: true
        isGlobal:
            type: boolean
            nullable: true
            column: is_global
        distanceTotal:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: distance_total
        distanceFirstRun:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: distance_first_run
        distanceLastRun:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: distance_last_run
        distanceSwim:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: distance_swim    
        distanceBike:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: distance_bike
    lifecycleCallbacks: {  }
    manyToMany:           
       events:
            targetEntity: Event
            inversedBy: categories
            joinTable:
                name: event_category
                joinColumns:
                      category_id:
                        referencedColumnName: id
                inverseJoinColumns:
                      event_id:
                        referencedColumnName: id
