<?php

namespace Proxies\__CG__\Amateur\ObjectBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Event extends \Amateur\ObjectBundle\Entity\Event implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getPuntuation()
    {
        $this->__load();
        return parent::getPuntuation();
    }

    public function setClassifications($name)
    {
        $this->__load();
        return parent::setClassifications($name);
    }

    public function getClassifications()
    {
        $this->__load();
        return parent::getClassifications();
    }

    public function addClassification($label)
    {
        $this->__load();
        return parent::addClassification($label);
    }

    public function removeClassification($label)
    {
        $this->__load();
        return parent::removeClassification($label);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setEmailContact($emailContact)
    {
        $this->__load();
        return parent::setEmailContact($emailContact);
    }

    public function getEmailContact()
    {
        $this->__load();
        return parent::getEmailContact();
    }

    public function setStartTime($startTime)
    {
        $this->__load();
        return parent::setStartTime($startTime);
    }

    public function getStartTime()
    {
        $this->__load();
        return parent::getStartTime();
    }

    public function setStartHs($startHs)
    {
        $this->__load();
        return parent::setStartHs($startHs);
    }

    public function getStartHs()
    {
        $this->__load();
        return parent::getStartHs();
    }

    public function setCreateTime($createTime)
    {
        $this->__load();
        return parent::setCreateTime($createTime);
    }

    public function getCreateTime()
    {
        $this->__load();
        return parent::getCreateTime();
    }

    public function setPhoto($photo)
    {
        $this->__load();
        return parent::setPhoto($photo);
    }

    public function getPhoto()
    {
        $this->__load();
        return parent::getPhoto();
    }

    public function setPhotoBackground($photoBackground)
    {
        $this->__load();
        return parent::setPhotoBackground($photoBackground);
    }

    public function getPhotoBackground()
    {
        $this->__load();
        return parent::getPhotoBackground();
    }

    public function setLinkPage($linkPage)
    {
        $this->__load();
        return parent::setLinkPage($linkPage);
    }

    public function getLinkPage()
    {
        $this->__load();
        return parent::getLinkPage();
    }

    public function setLabelLink($labelLink)
    {
        $this->__load();
        return parent::setLabelLink($labelLink);
    }

    public function getLabelLink()
    {
        $this->__load();
        return parent::getLabelLink();
    }

    public function setFlyerPath($flyerPath)
    {
        $this->__load();
        return parent::setFlyerPath($flyerPath);
    }

    public function getFlyerPath()
    {
        $this->__load();
        return parent::getFlyerPath();
    }

    public function getFilePhoto()
    {
        $this->__load();
        return parent::getFilePhoto();
    }

    public function getAbsolutePath()
    {
        $this->__load();
        return parent::getAbsolutePath();
    }

    public function getWebPath()
    {
        $this->__load();
        return parent::getWebPath();
    }

    public function setFilePhoto(\Symfony\Component\HttpFoundation\File\UploadedFile $filePhoto = NULL)
    {
        $this->__load();
        return parent::setFilePhoto($filePhoto);
    }

    public function upload()
    {
        $this->__load();
        return parent::upload();
    }

    public function removeUpload()
    {
        $this->__load();
        return parent::removeUpload();
    }

    public function getFilePhotoBackground()
    {
        $this->__load();
        return parent::getFilePhotoBackground();
    }

    public function getAbsolutePathB()
    {
        $this->__load();
        return parent::getAbsolutePathB();
    }

    public function getWebPathB()
    {
        $this->__load();
        return parent::getWebPathB();
    }

    public function setFilePhotoBackground(\Symfony\Component\HttpFoundation\File\UploadedFile $filePhotoBackground = NULL)
    {
        $this->__load();
        return parent::setFilePhotoBackground($filePhotoBackground);
    }

    public function uploadB()
    {
        $this->__load();
        return parent::uploadB();
    }

    public function removeUploadB()
    {
        $this->__load();
        return parent::removeUploadB();
    }

    public function getFileResult()
    {
        $this->__load();
        return parent::getFileResult();
    }

    public function getAbsolutePathFileResult()
    {
        $this->__load();
        return parent::getAbsolutePathFileResult();
    }

    public function getWebPathFileResult()
    {
        $this->__load();
        return parent::getWebPathFileResult();
    }

    public function setFileResult(\Symfony\Component\HttpFoundation\File\UploadedFile $file = NULL)
    {
        $this->__load();
        return parent::setFileResult($file);
    }

    public function uploadFileResult()
    {
        $this->__load();
        return parent::uploadFileResult();
    }

    public function removeUploadFileResult()
    {
        $this->__load();
        return parent::removeUploadFileResult();
    }

    public function setStartDate($startDate)
    {
        $this->__load();
        return parent::setStartDate($startDate);
    }

    public function getStartDate()
    {
        $this->__load();
        return parent::getStartDate();
    }

    public function getRegistrations()
    {
        $this->__load();
        return parent::getRegistrations();
    }

    public function setRegistrations(\Doctrine\Common\Collections\ArrayCollection $registrations)
    {
        $this->__load();
        return parent::setRegistrations($registrations);
    }

    public function getSport()
    {
        $this->__load();
        return parent::getSport();
    }

    public function setSport(\Amateur\ObjectBundle\Entity\Sport $sport)
    {
        $this->__load();
        return parent::setSport($sport);
    }

    public function getDistanceTotal()
    {
        $this->__load();
        return parent::getDistanceTotal();
    }

    public function setDistanceTotal($distanceTotal)
    {
        $this->__load();
        return parent::setDistanceTotal($distanceTotal);
    }

    public function getDistanceFirstRun()
    {
        $this->__load();
        return parent::getDistanceFirstRun();
    }

    public function setDistanceFirstRun($distanceFirstRun)
    {
        $this->__load();
        return parent::setDistanceFirstRun($distanceFirstRun);
    }

    public function getDistanceLastRun()
    {
        $this->__load();
        return parent::getDistanceLastRun();
    }

    public function setDistanceLastRun($distanceLastRun)
    {
        $this->__load();
        return parent::setDistanceLastRun($distanceLastRun);
    }

    public function getDistanceSwim()
    {
        $this->__load();
        return parent::getDistanceSwim();
    }

    public function setDistanceSwim($distanceSwim)
    {
        $this->__load();
        return parent::setDistanceSwim($distanceSwim);
    }

    public function getDistanceBike()
    {
        $this->__load();
        return parent::getDistanceBike();
    }

    public function setDistanceBike($distanceBike)
    {
        $this->__load();
        return parent::setDistanceBike($distanceBike);
    }

    public function getCategories()
    {
        $this->__load();
        return parent::getCategories();
    }

    public function setCategories($categories)
    {
        $this->__load();
        return parent::setCategories($categories);
    }

    public function addCategories($label)
    {
        $this->__load();
        return parent::addCategories($label);
    }

    public function removeCategories($label)
    {
        $this->__load();
        return parent::removeCategories($label);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getIsActive()
    {
        $this->__load();
        return parent::getIsActive();
    }

    public function setIsActive($isActive)
    {
        $this->__load();
        return parent::setIsActive($isActive);
    }

    public function getCity()
    {
        $this->__load();
        return parent::getCity();
    }

    public function setCity($city)
    {
        $this->__load();
        return parent::setCity($city);
    }

    public function getProvince()
    {
        $this->__load();
        return parent::getProvince();
    }

    public function setProvince($province)
    {
        $this->__load();
        return parent::setProvince($province);
    }

    public function getCountry()
    {
        $this->__load();
        return parent::getCountry();
    }

    public function setCountry($country)
    {
        $this->__load();
        return parent::setCountry($country);
    }

    public function getLatitude()
    {
        $this->__load();
        return parent::getLatitude();
    }

    public function setLatitude($latitude)
    {
        $this->__load();
        return parent::setLatitude($latitude);
    }

    public function getLongitude()
    {
        $this->__load();
        return parent::getLongitude();
    }

    public function setLongitude($longitude)
    {
        $this->__load();
        return parent::setLongitude($longitude);
    }

    public function getOrganizer()
    {
        $this->__load();
        return parent::getOrganizer();
    }

    public function setOrganizer(\Amateur\ObjectBundle\Entity\Organizer $organizer)
    {
        $this->__load();
        return parent::setOrganizer($organizer);
    }

    public function getDistanceMe()
    {
        $this->__load();
        return parent::getDistanceMe();
    }

    public function setDistanceMe($distanceMe)
    {
        $this->__load();
        return parent::setDistanceMe($distanceMe);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'isActive', 'emailContact', 'startTime', 'startHs', 'createTime', 'photo', 'photoBackground', 'linkPage', 'labelLink', 'flyerPath', 'startDate', 'distanceTotal', 'distanceFirstRun', 'distanceLastRun', 'distanceSwim', 'distanceBike', 'city', 'province', 'country', 'latitude', 'longitude', 'sport', 'classifications', 'registrations', 'organizer', 'categories');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}