<?php

namespace Proxies\__CG__\Xtending\EntityBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Contactos extends \Xtending\EntityBundle\Entity\Contactos implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCorporacion(\Xtending\EntityBundle\Entity\Corporaciones $corporacion = NULL)
    {
        $this->__load();
        return parent::setCorporacion($corporacion);
    }

    public function getCorporacion()
    {
        $this->__load();
        return parent::getCorporacion();
    }

    public function setEntidad(\Xtending\EntityBundle\Entity\Entidades $entidad = NULL)
    {
        $this->__load();
        return parent::setEntidad($entidad);
    }

    public function getEntidad()
    {
        $this->__load();
        return parent::getEntidad();
    }

    public function setSite($site)
    {
        $this->__load();
        return parent::setSite($site);
    }

    public function getSite()
    {
        $this->__load();
        return parent::getSite();
    }

    public function setCargo(\Xtending\EntityBundle\Entity\CargosEntidades $cargo)
    {
        $this->__load();
        return parent::setCargo($cargo);
    }

    public function getCargo()
    {
        $this->__load();
        return parent::getCargo();
    }

    public function setUsername($username)
    {
        $this->__load();
        return parent::setUsername($username);
    }

    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }

    public function getSalt()
    {
        $this->__load();
        return parent::getSalt();
    }

    public function setSalt($salt)
    {
        $this->__load();
        return parent::setSalt($salt);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getRoles()
    {
        $this->__load();
        return parent::getRoles();
    }

    public function addRole($role)
    {
        $this->__load();
        return parent::addRole($role);
    }

    public function getRolesNames()
    {
        $this->__load();
        return parent::getRolesNames();
    }

    public function setRoles($role)
    {
        $this->__load();
        return parent::setRoles($role);
    }

    public function getRolesCollection()
    {
        $this->__load();
        return parent::getRolesCollection();
    }

    public function setRolesCollection($roles)
    {
        $this->__load();
        return parent::setRolesCollection($roles);
    }

    public function setRole($role)
    {
        $this->__load();
        return parent::setRole($role);
    }

    public function getRole()
    {
        $this->__load();
        return parent::getRole();
    }

    public function eraseCredentials()
    {
        $this->__load();
        return parent::eraseCredentials();
    }

    public function serialize()
    {
        $this->__load();
        return parent::serialize();
    }

    public function unserialize($serialized)
    {
        $this->__load();
        return parent::unserialize($serialized);
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setApellido($apellido)
    {
        $this->__load();
        return parent::setApellido($apellido);
    }

    public function getApellido()
    {
        $this->__load();
        return parent::getApellido();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setTelefono($telefono)
    {
        $this->__load();
        return parent::setTelefono($telefono);
    }

    public function getTelefono()
    {
        $this->__load();
        return parent::getTelefono();
    }

    public function setCodigoRecuperacion($codigo)
    {
        $this->__load();
        return parent::setCodigoRecuperacion($codigo);
    }

    public function getCodigoRecuperacion()
    {
        $this->__load();
        return parent::getCodigoRecuperacion();
    }

    public function setCelular($celular)
    {
        $this->__load();
        return parent::setCelular($celular);
    }

    public function getCelular()
    {
        $this->__load();
        return parent::getCelular();
    }

    public function setDireccion($direccion)
    {
        $this->__load();
        return parent::setDireccion($direccion);
    }

    public function getDireccion()
    {
        $this->__load();
        return parent::getDireccion();
    }

    public function setFoto($foto)
    {
        $this->__load();
        return parent::setFoto($foto);
    }

    public function getFoto()
    {
        $this->__load();
        return parent::getFoto();
    }

    public function getIdioma()
    {
        $this->__load();
        return parent::getIdioma();
    }

    public function setIdioma($idioma)
    {
        $this->__load();
        return parent::setIdioma($idioma);
    }

    public function getTemplate()
    {
        $this->__load();
        return parent::getTemplate();
    }

    public function setTemplate($template)
    {
        $this->__load();
        return parent::setTemplate($template);
    }

    public function getFile()
    {
        $this->__load();
        return parent::getFile();
    }

    public function getAbsolutePath()
    {
        $this->__load();
        return parent::getAbsolutePath();
    }

    public function getWebPath()
    {
        $this->__load();
        return parent::getWebPath();
    }

    public function setFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file = NULL)
    {
        $this->__load();
        return parent::setFile($file);
    }

    public function upload()
    {
        $this->__load();
        return parent::upload();
    }

    public function removeUpload()
    {
        $this->__load();
        return parent::removeUpload();
    }

    public function getTipoUsuario()
    {
        $this->__load();
        return parent::getTipoUsuario();
    }

    public function setTyc($valor)
    {
        $this->__load();
        return parent::setTyc($valor);
    }

    public function getTyc()
    {
        $this->__load();
        return parent::getTyc();
    }

    public function getSites()
    {
        $this->__load();
        return parent::getSites();
    }

    public function addSites($site)
    {
        $this->__load();
        return parent::addSites($site);
    }

    public function removeSites($site)
    {
        $this->__load();
        return parent::removeSites($site);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getPlanificaciones()
    {
        $this->__load();
        return parent::getPlanificaciones();
    }

    public function addPlanificaciones($planificacion)
    {
        $this->__load();
        return parent::addPlanificaciones($planificacion);
    }

    public function removePlanificaciones($planificacion)
    {
        $this->__load();
        return parent::removePlanificaciones($planificacion);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'username', 'salt', 'password', 'isActive', 'nombre', 'apellido', 'email', 'codigoRecuperacion', 'telefono', 'celular', 'direccion', 'foto', 'idioma', 'template', 'tyc', 'cargo', 'planificaciones', 'entidad', 'site', 'corporacion', 'roles', 'sites');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}