<?php

namespace Proxies\__CG__\Xtending\EntityBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Sites extends \Xtending\EntityBundle\Entity\Sites implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getContactos()
    {
        $this->__load();
        return parent::getContactos();
    }

    public function addContactos($contactos)
    {
        $this->__load();
        return parent::addContactos($contactos);
    }

    public function removeContactos($contactos)
    {
        $this->__load();
        return parent::removeContactos($contactos);
    }

    public function getResponsables()
    {
        $this->__load();
        return parent::getResponsables();
    }

    public function addResponsables($contacto)
    {
        $this->__load();
        return parent::addResponsables($contacto);
    }

    public function removeResponsables($contacto)
    {
        $this->__load();
        return parent::removeResponsables($contacto);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setOperador($operador)
    {
        $this->__load();
        return parent::setOperador($operador);
    }

    public function getOperador()
    {
        $this->__load();
        return parent::getOperador();
    }

    public function setPais(\Xtending\EntityBundle\Entity\Paises $pais = NULL)
    {
        $this->__load();
        return parent::setPais($pais);
    }

    public function getPais()
    {
        $this->__load();
        return parent::getPais();
    }

    public function setCiudad($ciudad)
    {
        $this->__load();
        return parent::setCiudad($ciudad);
    }

    public function getCiudad()
    {
        $this->__load();
        return parent::getCiudad();
    }

    public function setEstado($estado)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }

    public function setDomicilio($domicilio)
    {
        $this->__load();
        return parent::setDomicilio($domicilio);
    }

    public function getDomicilio()
    {
        $this->__load();
        return parent::getDomicilio();
    }

    public function setCodpostal($codpostal)
    {
        $this->__load();
        return parent::setCodpostal($codpostal);
    }

    public function getCodpostal()
    {
        $this->__load();
        return parent::getCodpostal();
    }

    public function setLogo($logo)
    {
        $this->__load();
        return parent::setLogo($logo);
    }

    public function getLogo()
    {
        $this->__load();
        return parent::getLogo();
    }

    public function setFechaalta($fechaalta)
    {
        $this->__load();
        return parent::setFechaalta($fechaalta);
    }

    public function getFechaalta()
    {
        $this->__load();
        return parent::getFechaalta();
    }

    public function setTelefonos($telefonos)
    {
        $this->__load();
        return parent::setTelefonos($telefonos);
    }

    public function getTelefonos()
    {
        $this->__load();
        return parent::getTelefonos();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setEmailAlternativo($email)
    {
        $this->__load();
        return parent::setEmailAlternativo($email);
    }

    public function getEmailAlternativo()
    {
        $this->__load();
        return parent::getEmailAlternativo();
    }

    public function setWeb($web)
    {
        $this->__load();
        return parent::setWeb($web);
    }

    public function getWeb()
    {
        $this->__load();
        return parent::getWeb();
    }

    public function setDescripcionProductos($descripcion)
    {
        $this->__load();
        return parent::setDescripcionProductos($descripcion);
    }

    public function getDescripcionProductos()
    {
        $this->__load();
        return parent::getDescripcionProductos();
    }

    public function setDescripcionSite($descripcion)
    {
        $this->__load();
        return parent::setDescripcionSite($descripcion);
    }

    public function getDescripcionSite()
    {
        $this->__load();
        return parent::getDescripcionSite();
    }

    public function setCodigoplanta($codigoplanta)
    {
        $this->__load();
        return parent::setCodigoplanta($codigoplanta);
    }

    public function getCodigoplanta()
    {
        $this->__load();
        return parent::getCodigoplanta();
    }

    public function setAdjunto($adjunto)
    {
        $this->__load();
        return parent::setAdjunto($adjunto);
    }

    public function getAdjunto()
    {
        $this->__load();
        return parent::getAdjunto();
    }

    public function setEntidad(\Xtending\EntityBundle\Entity\Entidades $entidad = NULL)
    {
        $this->__load();
        return parent::setEntidad($entidad);
    }

    public function getEntidad()
    {
        $this->__load();
        return parent::getEntidad();
    }

    public function setContacto(\Xtending\EntityBundle\Entity\Contactos $contacto = NULL)
    {
        $this->__load();
        return parent::setContacto($contacto);
    }

    public function getContacto()
    {
        $this->__load();
        return parent::getContacto();
    }

    public function getFile()
    {
        $this->__load();
        return parent::getFile();
    }

    public function getAbsolutePath()
    {
        $this->__load();
        return parent::getAbsolutePath();
    }

    public function getWebPath()
    {
        $this->__load();
        return parent::getWebPath();
    }

    public function setFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file = NULL)
    {
        $this->__load();
        return parent::setFile($file);
    }

    public function upload()
    {
        $this->__load();
        return parent::upload();
    }

    public function removeUpload()
    {
        $this->__load();
        return parent::removeUpload();
    }

    public function esPropiaEntidad($usuario)
    {
        $this->__load();
        return parent::esPropiaEntidad($usuario);
    }

    public function getEntidadId()
    {
        $this->__load();
        return parent::getEntidadId();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'operador', 'ciudad', 'estado', 'domicilio', 'codpostal', 'logo', 'fechaalta', 'telefonos', 'email', 'emailAlternativo', 'web', 'descripcionSite', 'descripcionProductos', 'codigoplanta', 'adjunto', 'contactos', 'entidad', 'contacto', 'pais', 'responsables');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}