<?php

namespace Proxies\__CG__\Xtending\EntityBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class FormulariosDefiniciones extends \Xtending\EntityBundle\Entity\FormulariosDefiniciones implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setFormularioConfiguracion(\Xtending\EntityBundle\Entity\FormularioConfiguracion $formularioConfiguracion)
    {
        $this->__load();
        return parent::setFormularioConfiguracion($formularioConfiguracion);
    }

    public function getFormularioConfiguracion()
    {
        $this->__load();
        return parent::getFormularioConfiguracion();
    }

    public function setCodigoDinamico(\Xtending\EntityBundle\Entity\CodigoFD $codigo)
    {
        $this->__load();
        return parent::setCodigoDinamico($codigo);
    }

    public function getCodigoDinamico()
    {
        $this->__load();
        return parent::getCodigoDinamico();
    }

    public function getGruposPregunta()
    {
        $this->__load();
        return parent::getGruposPregunta();
    }

    public function addGrupospregunton($grupoPregunta)
    {
        $this->__load();
        return parent::addGrupospregunton($grupoPregunta);
    }

    public function removeGrupospregunton($gruposPregunta)
    {
        $this->__load();
        return parent::removeGrupospregunton($gruposPregunta);
    }

    public function getLabelsCaratula()
    {
        $this->__load();
        return parent::getLabelsCaratula();
    }

    public function addLabelsCaratulon($label)
    {
        $this->__load();
        return parent::addLabelsCaratulon($label);
    }

    public function removeLabelsCaratulon($label)
    {
        $this->__load();
        return parent::removeLabelsCaratulon($label);
    }

    public function getEstados()
    {
        $this->__load();
        return parent::getEstados();
    }

    public function addEstado($estado)
    {
        $this->__load();
        return parent::addEstado($estado);
    }

    public function removeEstado($estado)
    {
        $this->__load();
        return parent::removeEstado($estado);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setTienefechaautomatica($tienefecha)
    {
        $this->__load();
        return parent::setTienefechaautomatica($tienefecha);
    }

    public function getTienefechaautomatica()
    {
        $this->__load();
        return parent::getTienefechaautomatica();
    }

    public function setTienefechacierre($tienefecha)
    {
        $this->__load();
        return parent::setTienefechacierre($tienefecha);
    }

    public function getTienefechacierre()
    {
        $this->__load();
        return parent::getTienefechacierre();
    }

    public function getTieneProducto()
    {
        $this->__load();
        return parent::getTieneProducto();
    }

    public function setTieneProducto($tieneProducto)
    {
        $this->__load();
        return parent::setTieneProducto($tieneProducto);
    }

    public function setTienesite($tienesite)
    {
        $this->__load();
        return parent::setTienesite($tienesite);
    }

    public function getTieneempresa()
    {
        $this->__load();
        return parent::getTieneempresa();
    }

    public function setTieneempresa($tieneempresa)
    {
        $this->__load();
        return parent::setTieneempresa($tieneempresa);
    }

    public function getTienesite()
    {
        $this->__load();
        return parent::getTienesite();
    }

    public function setTienecodigo($codigo)
    {
        $this->__load();
        return parent::setTienecodigo($codigo);
    }

    public function getTienecodigo()
    {
        $this->__load();
        return parent::getTienecodigo();
    }

    public function setTieneproveedor($tieneproveedor)
    {
        $this->__load();
        return parent::setTieneproveedor($tieneproveedor);
    }

    public function getTieneproveedor()
    {
        $this->__load();
        return parent::getTieneproveedor();
    }

    public function setTienefechamanual($tienefechamanual)
    {
        $this->__load();
        return parent::setTienefechamanual($tienefechamanual);
    }

    public function getTienefechamanual()
    {
        $this->__load();
        return parent::getTienefechamanual();
    }

    public function setTieneContacto($tieneContacto)
    {
        $this->__load();
        return parent::setTieneContacto($tieneContacto);
    }

    public function getTieneContacto()
    {
        $this->__load();
        return parent::getTieneContacto();
    }

    public function setTieneContactoEntidad($tieneContacto)
    {
        $this->__load();
        return parent::setTieneContactoEntidad($tieneContacto);
    }

    public function getTieneContactoEntidad()
    {
        $this->__load();
        return parent::getTieneContactoEntidad();
    }

    public function setTieneCapitulos($capitulos)
    {
        $this->__load();
        return parent::setTieneCapitulos($capitulos);
    }

    public function getTieneCapitulos()
    {
        $this->__load();
        return parent::getTieneCapitulos();
    }

    public function setDescripcionEstado($descripcionEstado)
    {
        $this->__load();
        return parent::setDescripcionEstado($descripcionEstado);
    }

    public function getDescripcionEstado()
    {
        $this->__load();
        return parent::getDescripcionEstado();
    }

    public function setTieneResumen($tieneResumen)
    {
        $this->__load();
        return parent::setTieneResumen($tieneResumen);
    }

    public function getBotonNoevalua()
    {
        $this->__load();
        return parent::getBotonNoevalua();
    }

    public function setBotonNoevalua($botonNoevalua)
    {
        $this->__load();
        return parent::setBotonNoevalua($botonNoevalua);
    }

    public function getTieneResumen()
    {
        $this->__load();
        return parent::getTieneResumen();
    }

    public function setCaratula($caratula)
    {
        $this->__load();
        return parent::setCaratula($caratula);
    }

    public function getCaratula()
    {
        $this->__load();
        return parent::getCaratula();
    }

    public function setActivo($activo)
    {
        $this->__load();
        return parent::setActivo($activo);
    }

    public function getActivo()
    {
        $this->__load();
        return parent::getActivo();
    }

    public function setTieneHistorial($valor)
    {
        $this->__load();
        return parent::setTieneHistorial($valor);
    }

    public function getTieneHistorial()
    {
        $this->__load();
        return parent::getTieneHistorial();
    }

    public function setTipoFormulario($valor)
    {
        $this->__load();
        return parent::setTipoFormulario($valor);
    }

    public function getTipoFormulario()
    {
        $this->__load();
        return parent::getTipoFormulario();
    }

    public function setTienePac($valor)
    {
        $this->__load();
        return parent::setTienePac($valor);
    }

    public function getTienePac()
    {
        $this->__load();
        return parent::getTienePac();
    }

    public function setTieneCopia($valor)
    {
        $this->__load();
        return parent::setTieneCopia($valor);
    }

    public function getAgrupable()
    {
        $this->__load();
        return parent::getAgrupable();
    }

    public function setAgrupable($valor)
    {
        $this->__load();
        return parent::setAgrupable($valor);
    }

    public function getTieneCopia()
    {
        $this->__load();
        return parent::getTieneCopia();
    }

    public function setTienePdf($valor)
    {
        $this->__load();
        return parent::setTienePdf($valor);
    }

    public function getTienePdf()
    {
        $this->__load();
        return parent::getTienePdf();
    }

    public function setConfig(\Xtending\EntityBundle\Entity\ConfigCustom $config = NULL)
    {
        $this->__load();
        return parent::setConfig($config);
    }

    public function getConfig()
    {
        $this->__load();
        return parent::getConfig();
    }

    public function getCodigoManual()
    {
        $this->__load();
        return parent::getCodigoManual();
    }

    public function setCodigoManual($valor)
    {
        $this->__load();
        return parent::setCodigoManual($valor);
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'tienefechaautomatica', 'caratula', 'tienesite', 'tieneProducto', 'tieneempresa', 'tienecodigo', 'tieneproveedor', 'tienefechamanual', 'tienefechacierre', 'tieneContacto', 'tieneContactoEntidad', 'tieneCapitulos', 'descripcionEstado', 'tieneResumen', 'botonNoevalua', 'activo', 'tieneHistorial', 'tienePac', 'tieneCopia', 'agrupable', 'tienePdf', 'codigoManual', 'formularioConfiguracion', 'codigoDinamico', 'tipoFormulario', 'labelsCaratula', 'gruposPregunta', 'estados', 'config');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}