<?php

namespace Proxies\__CG__\Xtending\EntityBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ConfigCustom extends \Xtending\EntityBundle\Entity\ConfigCustom implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getFormulariosDefiniciones()
    {
        $this->__load();
        return parent::getFormulariosDefiniciones();
    }

    public function addFormulariosDefiniciones($fd)
    {
        $this->__load();
        return parent::addFormulariosDefiniciones($fd);
    }

    public function removeFormulariosDefiniciones($fd)
    {
        $this->__load();
        return parent::removeFormulariosDefiniciones($fd);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setTienePac($valor)
    {
        $this->__load();
        return parent::setTienePac($valor);
    }

    public function getTienePac()
    {
        $this->__load();
        return parent::getTienePac();
    }

    public function setTienePdf($valor)
    {
        $this->__load();
        return parent::setTienePdf($valor);
    }

    public function getTienePdf()
    {
        $this->__load();
        return parent::getTienePdf();
    }

    public function setTienePdfFull($valor)
    {
        $this->__load();
        return parent::setTienePdfFull($valor);
    }

    public function getTienePdfFull()
    {
        $this->__load();
        return parent::getTienePdfFull();
    }

    public function setTieneResumen($valor)
    {
        $this->__load();
        return parent::setTieneResumen($valor);
    }

    public function getTieneResumen()
    {
        $this->__load();
        return parent::getTieneResumen();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'tienePac', 'tienePdf', 'tienePdfFull', 'tieneResumen', 'formulariosDefiniciones');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}