<?php

namespace Proxies\__CG__\Xtending\EntityBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class FormulariosResultados extends \Xtending\EntityBundle\Entity\FormulariosResultados implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setDiscr($discr)
    {
        $this->__load();
        return parent::setDiscr($discr);
    }

    public function getDiscr()
    {
        $this->__load();
        return parent::getDiscr();
    }

    public function getEstadosFormularioValor()
    {
        $this->__load();
        return parent::getEstadosFormularioValor();
    }

    public function addEstadosFormularioValor($estadosFormularioValor)
    {
        $this->__load();
        return parent::addEstadosFormularioValor($estadosFormularioValor);
    }

    public function removeEstadosFormularioValor($estadosFormularioValor)
    {
        $this->__load();
        return parent::removeEstadosFormularioValor($estadosFormularioValor);
    }

    public function getAccionesCorrectivas()
    {
        $this->__load();
        return parent::getAccionesCorrectivas();
    }

    public function addAccionesCorrectiva($accionCorrectiva)
    {
        $this->__load();
        return parent::addAccionesCorrectiva($accionCorrectiva);
    }

    public function removeAccionesCorrectiva($accionCorrectiva)
    {
        $this->__load();
        return parent::removeAccionesCorrectiva($accionCorrectiva);
    }

    public function getLabelsCaratulaFile()
    {
        $this->__load();
        return parent::getLabelsCaratulaFile();
    }

    public function addLabelsCaratulaFile($file)
    {
        $this->__load();
        return parent::addLabelsCaratulaFile($file);
    }

    public function removeLabelsCaratulaFile($file)
    {
        $this->__load();
        return parent::removeLabelsCaratulaFile($file);
    }

    public function getPreguntasValor()
    {
        $this->__load();
        return parent::getPreguntasValor();
    }

    public function getPreguntasResumenGrupo($grupo)
    {
        $this->__load();
        return parent::getPreguntasResumenGrupo($grupo);
    }

    public function addPreguntasValor($preguntasValor)
    {
        $this->__load();
        return parent::addPreguntasValor($preguntasValor);
    }

    public function removePreguntasValor($preguntasValor)
    {
        $this->__load();
        return parent::removePreguntasValor($preguntasValor);
    }

    public function getFormulariosResultadosHistorial()
    {
        $this->__load();
        return parent::getFormulariosResultadosHistorial();
    }

    public function addFormulariosResultadosHistorial($formulariosResultadosHistorial)
    {
        $this->__load();
        return parent::addFormulariosResultadosHistorial($formulariosResultadosHistorial);
    }

    public function removeFormulariosResultadosHistorial($formulariosResultadosHistorial)
    {
        $this->__load();
        return parent::removeFormulariosResultadosHistorial($formulariosResultadosHistorial);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setFechaautomatica($fechaautomatica)
    {
        $this->__load();
        return parent::setFechaautomatica($fechaautomatica);
    }

    public function getFechaautomatica()
    {
        $this->__load();
        return parent::getFechaautomatica();
    }

    public function setFechamanual($fechamanual)
    {
        $this->__load();
        return parent::setFechamanual($fechamanual);
    }

    public function getFechamanual()
    {
        $this->__load();
        return parent::getFechamanual();
    }

    public function setFechaCierre($fechaCierre)
    {
        $this->__load();
        return parent::setFechaCierre($fechaCierre);
    }

    public function getFechaCierre()
    {
        $this->__load();
        return parent::getFechaCierre();
    }

    public function setFormulariosDefiniciones($formulariosDefiniciones)
    {
        $this->__load();
        return parent::setFormulariosDefiniciones($formulariosDefiniciones);
    }

    public function getFormulariosDefiniciones()
    {
        $this->__load();
        return parent::getFormulariosDefiniciones();
    }

    public function setlabelsCaratulaValor($label)
    {
        $this->__load();
        return parent::setlabelsCaratulaValor($label);
    }

    public function addLabelsCaratulaValor($label)
    {
        $this->__load();
        return parent::addLabelsCaratulaValor($label);
    }

    public function removeLabelsCaratulaValor($label)
    {
        $this->__load();
        return parent::removeLabelsCaratulaValor($label);
    }

    public function getLabelsCaratulaValor()
    {
        $this->__load();
        return parent::getLabelsCaratulaValor();
    }

    public function setContacto(\Xtending\EntityBundle\Entity\Contactos $contacto = NULL)
    {
        $this->__load();
        return parent::setContacto($contacto);
    }

    public function getContacto()
    {
        $this->__load();
        return parent::getContacto();
    }

    public function setContactoEntidad(\Xtending\EntityBundle\Entity\Contactos $contacto = NULL)
    {
        $this->__load();
        return parent::setContactoEntidad($contacto);
    }

    public function getContactoEntidad()
    {
        $this->__load();
        return parent::getContactoEntidad();
    }

    public function setProveedor(\Xtending\EntityBundle\Entity\Entidades $entidad = NULL)
    {
        $this->__load();
        return parent::setProveedor($entidad);
    }

    public function getProveedor()
    {
        $this->__load();
        return parent::getProveedor();
    }

    public function setCompartido(\Xtending\EntityBundle\Entity\AsignacionIndividual $ai = NULL)
    {
        $this->__load();
        return parent::setCompartido($ai);
    }

    public function getCompartido()
    {
        $this->__load();
        return parent::getCompartido();
    }

    public function setSite(\Xtending\EntityBundle\Entity\Sites $site = NULL)
    {
        $this->__load();
        return parent::setSite($site);
    }

    public function getSite()
    {
        $this->__load();
        return parent::getSite();
    }

    public function setEmpresa(\Xtending\EntityBundle\Entity\Entidades $empresa = NULL)
    {
        $this->__load();
        return parent::setEmpresa($empresa);
    }

    public function getEmpresa()
    {
        $this->__load();
        return parent::getEmpresa();
    }

    public function getProducto()
    {
        $this->__load();
        return parent::getProducto();
    }

    public function setProducto(\Xtending\EntityBundle\Entity\Producto $producto = NULL)
    {
        $this->__load();
        return parent::setProducto($producto);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }

    public function getEstadoNombre()
    {
        $this->__load();
        return parent::getEstadoNombre();
    }

    public function setEstado($estado)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function setPrivado($valor)
    {
        $this->__load();
        return parent::setPrivado($valor);
    }

    public function getPrivado()
    {
        $this->__load();
        return parent::getPrivado();
    }

    public function setEliminado($estado)
    {
        $this->__load();
        return parent::setEliminado($estado);
    }

    public function getEliminado()
    {
        $this->__load();
        return parent::getEliminado();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function setModificadoPor($modificadoPor)
    {
        $this->__load();
        return parent::setModificadoPor($modificadoPor);
    }

    public function getModificadoPor()
    {
        $this->__load();
        return parent::getModificadoPor();
    }

    public function setFechaModificado($fechaModificado)
    {
        $this->__load();
        return parent::setFechaModificado($fechaModificado);
    }

    public function getFechaModificado()
    {
        $this->__load();
        return parent::getFechaModificado();
    }

    public function setComentario($comentario)
    {
        $this->__load();
        return parent::setComentario($comentario);
    }

    public function getComentario()
    {
        $this->__load();
        return parent::getComentario();
    }

    public function setVersion($version)
    {
        $this->__load();
        return parent::setVersion($version);
    }

    public function getVersion()
    {
        $this->__load();
        return parent::getVersion();
    }

    public function getHistorialRegistro()
    {
        $this->__load();
        return parent::getHistorialRegistro();
    }

    public function getRegistrosByHistorial()
    {
        $this->__load();
        return parent::getRegistrosByHistorial();
    }

    public function esCompartible()
    {
        $this->__load();
        return parent::esCompartible();
    }

    public function getIdByTipoEntidad()
    {
        $this->__load();
        return parent::getIdByTipoEntidad();
    }

    public function setEntidad($entidad)
    {
        $this->__load();
        return parent::setEntidad($entidad);
    }

    public function getEntidad()
    {
        $this->__load();
        return parent::getEntidad();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'fechaautomatica', 'fechamanual', 'fechaCierre', 'eliminado', 'estado', 'privado', 'preguntasValor', 'labelsCaratulaValor', 'labelsCaratulaFile', 'estadosFormularioValor', 'accionesCorrectivas', 'formulariosResultadosHistorial', 'formulariosDefiniciones', 'contacto', 'contactoEntidad', 'proveedor', 'compartido', 'site', 'producto', 'empresa');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}