<?php

namespace Proxies\__CG__\Xtending\EntityBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Alerta extends \Xtending\EntityBundle\Entity\Alerta implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setRemitente($remitente = NULL)
    {
        $this->__load();
        return parent::setRemitente($remitente);
    }

    public function getRemitente()
    {
        $this->__load();
        return parent::getRemitente();
    }

    public function setFormularioDefinicion($formulario)
    {
        $this->__load();
        return parent::setFormularioDefinicion($formulario);
    }

    public function getFormularioDefinicion()
    {
        $this->__load();
        return parent::getFormularioDefinicion();
    }

    public function setAsunto($asunto = NULL)
    {
        $this->__load();
        return parent::setAsunto($asunto);
    }

    public function getAsunto()
    {
        $this->__load();
        return parent::getAsunto();
    }

    public function setContenido($contenido = NULL)
    {
        $this->__load();
        return parent::setContenido($contenido);
    }

    public function getContenido()
    {
        $this->__load();
        return parent::getContenido();
    }

    public function setDestinatario($destinatario = NULL)
    {
        $this->__load();
        return parent::setDestinatario($destinatario);
    }

    public function getDestinatario()
    {
        $this->__load();
        return parent::getDestinatario();
    }

    public function setTipoDestinatario($tipoDestinatario = NULL)
    {
        $this->__load();
        return parent::setTipoDestinatario($tipoDestinatario);
    }

    public function getTipoDestinatario()
    {
        $this->__load();
        return parent::getTipoDestinatario();
    }

    public function setTipoRepeticion($tipo = NULL)
    {
        $this->__load();
        return parent::setTipoRepeticion($tipo);
    }

    public function getTipoRepeticion()
    {
        $this->__load();
        return parent::getTipoRepeticion();
    }

    public function setTipoBase($tipoBase = NULL)
    {
        $this->__load();
        return parent::setTipoBase($tipoBase);
    }

    public function getTipoBase()
    {
        $this->__load();
        return parent::getTipoBase();
    }

    public function setBaseDato($baseDato = NULL)
    {
        $this->__load();
        return parent::setBaseDato($baseDato);
    }

    public function getBaseDato()
    {
        $this->__load();
        return parent::getBaseDato();
    }

    public function setRepeticionDato($repeticionDato = NULL)
    {
        $this->__load();
        return parent::setRepeticionDato($repeticionDato);
    }

    public function getRepeticionDato()
    {
        $this->__load();
        return parent::getRepeticionDato();
    }

    public function setTipoFin($tipoFin = NULL)
    {
        $this->__load();
        return parent::setTipoFin($tipoFin);
    }

    public function getTipoFin()
    {
        $this->__load();
        return parent::getTipoFin();
    }

    public function setFinDato($finDato = NULL)
    {
        $this->__load();
        return parent::setFinDato($finDato);
    }

    public function getFinDato()
    {
        $this->__load();
        return parent::getFinDato();
    }

    public function setCounter($counter = NULL)
    {
        $this->__load();
        return parent::setCounter($counter);
    }

    public function getCounter()
    {
        $this->__load();
        return parent::getCounter();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'remitente', 'asunto', 'contenido', 'destinatario', 'tipoRepeticion', 'tipoDestinatario', 'repeticionDato', 'tipoBase', 'finDato', 'tipoFin', 'formularioDefinicion');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}