<?php

namespace Proxies\__CG__\Xtending\EntityBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Preguntas extends \Xtending\EntityBundle\Entity\Preguntas implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function addGrupoPregunta(\Xtending\EntityBundle\Entity\GrupoPregunta $grupoPregunta)
    {
        $this->__load();
        return parent::addGrupoPregunta($grupoPregunta);
    }

    public function getGrupoPregunta()
    {
        $this->__load();
        return parent::getGrupoPregunta();
    }

    public function setGrupoPregunta(\Xtending\EntityBundle\Entity\GrupoPregunta $grupoPregunta)
    {
        $this->__load();
        return parent::setGrupoPregunta($grupoPregunta);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTieneTextarea($tieneTextarea)
    {
        $this->__load();
        return parent::setTieneTextarea($tieneTextarea);
    }

    public function setDestacado($destacado)
    {
        $this->__load();
        return parent::setDestacado($destacado);
    }

    public function getDestacado()
    {
        $this->__load();
        return parent::getDestacado();
    }

    public function setResumen($valor)
    {
        $this->__load();
        return parent::setResumen($valor);
    }

    public function getResumen()
    {
        $this->__load();
        return parent::getResumen();
    }

    public function getTieneTextarea()
    {
        $this->__load();
        return parent::getTieneTextarea();
    }

    public function getTieneText()
    {
        $this->__load();
        return parent::getTieneText();
    }

    public function setTieneText($valor)
    {
        $this->__load();
        return parent::setTieneText($valor);
    }

    public function getTieneAyuda()
    {
        $this->__load();
        return parent::getTieneAyuda();
    }

    public function getTieneUnidad()
    {
        $this->__load();
        return parent::getTieneUnidad();
    }

    public function getCriterio()
    {
        $this->__load();
        return parent::getCriterio();
    }

    public function setCriterio(\Xtending\EntityBundle\Entity\Criterios $criterio)
    {
        $this->__load();
        return parent::setCriterio($criterio);
    }

    public function setTieneAyuda($tieneAyuda)
    {
        $this->__load();
        return parent::setTieneAyuda($tieneAyuda);
    }

    public function setTieneUnidad($unidad)
    {
        $this->__load();
        return parent::setTieneUnidad($unidad);
    }

    public function setTieneAccionCorrectiva($tieneAccionCorrectiva)
    {
        $this->__load();
        return parent::setTieneAccionCorrectiva($tieneAccionCorrectiva);
    }

    public function getTieneAccionCorrectiva()
    {
        $this->__load();
        return parent::getTieneAccionCorrectiva();
    }

    public function setPunto($punto)
    {
        $this->__load();
        return parent::setPunto($punto);
    }

    public function getPunto()
    {
        $this->__load();
        return parent::getPunto();
    }

    public function setDescripcion($descripcion)
    {
        $this->__load();
        return parent::setDescripcion($descripcion);
    }

    public function getDescripcion()
    {
        $this->__load();
        return parent::getDescripcion();
    }

    public function setTieneFecha($tieneFecha)
    {
        $this->__load();
        return parent::setTieneFecha($tieneFecha);
    }

    public function getTieneFecha()
    {
        $this->__load();
        return parent::getTieneFecha();
    }

    public function setTieneArchivo($tieneArchivo)
    {
        $this->__load();
        return parent::setTieneArchivo($tieneArchivo);
    }

    public function getTieneArchivo()
    {
        $this->__load();
        return parent::getTieneArchivo();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'punto', 'resumen', 'tieneText', 'tieneFecha', 'tieneArchivo', 'descripcion', 'tieneTextarea', 'destacado', 'tieneAyuda', 'tieneUnidad', 'tieneAccionCorrectiva', 'grupoPregunta', 'criterio');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}