<?php

namespace Proxies\__CG__\Xtending\EntityBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CausaPropuesta extends \Xtending\EntityBundle\Entity\CausaPropuesta implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setDescripcionAnalisis($descripcionAnalisis)
    {
        $this->__load();
        return parent::setDescripcionAnalisis($descripcionAnalisis);
    }

    public function getDescripcionAnalisis()
    {
        $this->__load();
        return parent::getDescripcionAnalisis();
    }

    public function setArchivoAnalisis($archivoAnalisis)
    {
        $this->__load();
        return parent::setArchivoAnalisis($archivoAnalisis);
    }

    public function getArchivoAnalisis()
    {
        $this->__load();
        return parent::getArchivoAnalisis();
    }

    public function setFechaAnalisis($fechaAnalisis)
    {
        $this->__load();
        return parent::setFechaAnalisis($fechaAnalisis);
    }

    public function getFechaAnalisis()
    {
        $this->__load();
        return parent::getFechaAnalisis();
    }

    public function setAutor($autor)
    {
        $this->__load();
        return parent::setAutor($autor);
    }

    public function getAutor()
    {
        $this->__load();
        return parent::getAutor();
    }

    public function getAccionesCorrectivas()
    {
        $this->__load();
        return parent::getAccionesCorrectivas();
    }

    public function addAccionesCorrectiva($accionCorrectiva)
    {
        $this->__load();
        return parent::addAccionesCorrectiva($accionCorrectiva);
    }

    public function removeAccionesCorrectiva($accionCorrectiva)
    {
        $this->__load();
        return parent::removeAccionesCorrectiva($accionCorrectiva);
    }

    public function getFile()
    {
        $this->__load();
        return parent::getFile();
    }

    public function getAbsolutePath()
    {
        $this->__load();
        return parent::getAbsolutePath();
    }

    public function getWebPath()
    {
        $this->__load();
        return parent::getWebPath();
    }

    public function setFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file = NULL)
    {
        $this->__load();
        return parent::setFile($file);
    }

    public function upload()
    {
        $this->__load();
        return parent::upload();
    }

    public function removeUpload()
    {
        $this->__load();
        return parent::removeUpload();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'descripcionAnalisis', 'archivoAnalisis', 'fechaAnalisis', 'autor', 'accionCorrectiva');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}