<?php

namespace Proxies\__CG__\Xtending\EntityBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntidadFormularios extends \Xtending\EntityBundle\Entity\EntidadFormularios implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getEntidadesCompartidas()
    {
        $this->__load();
        return parent::getEntidadesCompartidas();
    }

    public function setEntidadesCompartidas($entidadesCompartidas)
    {
        $this->__load();
        return parent::setEntidadesCompartidas($entidadesCompartidas);
    }

    public function setFecha($fecha)
    {
        $this->__load();
        return parent::setFecha($fecha);
    }

    public function getFecha()
    {
        $this->__load();
        return parent::getFecha();
    }

    public function setEntidad(\Xtending\EntityBundle\Entity\Entidades $entidad = NULL)
    {
        $this->__load();
        return parent::setEntidad($entidad);
    }

    public function getEntidad()
    {
        $this->__load();
        return parent::getEntidad();
    }

    public function setFormulariodefinicion(\Xtending\EntityBundle\Entity\FormulariosDefiniciones $formulariodefinicion = NULL)
    {
        $this->__load();
        return parent::setFormulariodefinicion($formulariodefinicion);
    }

    public function getFormulariodefinicion()
    {
        $this->__load();
        return parent::getFormulariodefinicion();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function setEsProveedor($esProveedor)
    {
        $this->__load();
        return parent::setEsProveedor($esProveedor);
    }

    public function getEsProveedor()
    {
        $this->__load();
        return parent::getEsProveedor();
    }

    public function setEsPrivada($esPrivada)
    {
        $this->__load();
        return parent::setEsPrivada($esPrivada);
    }

    public function getEsPrivada()
    {
        $this->__load();
        return parent::getEsPrivada();
    }

    public function setSoyProveedor($proveedor)
    {
        $this->__load();
        return parent::setSoyProveedor($proveedor);
    }

    public function getSoyProveedor()
    {
        $this->__load();
        return parent::getSoyProveedor();
    }

    public function setEsProveedorProducto($esProveedorProducto)
    {
        $this->__load();
        return parent::setEsProveedorProducto($esProveedorProducto);
    }

    public function getEsProveedorProducto()
    {
        $this->__load();
        return parent::getEsProveedorProducto();
    }

    public function setEsCliente($esCliente)
    {
        $this->__load();
        return parent::setEsCliente($esCliente);
    }

    public function getEsCliente()
    {
        $this->__load();
        return parent::getEsCliente();
    }

    public function setSoyCliente($cliente)
    {
        $this->__load();
        return parent::setSoyCliente($cliente);
    }

    public function getSoyCliente()
    {
        $this->__load();
        return parent::getSoyCliente();
    }

    public function setEsClienteProducto($esClienteProducto)
    {
        $this->__load();
        return parent::setEsClienteProducto($esClienteProducto);
    }

    public function getEsClienteProducto()
    {
        $this->__load();
        return parent::getEsClienteProducto();
    }

    public function setEsPropioSite($esPropioSite)
    {
        $this->__load();
        return parent::setEsPropioSite($esPropioSite);
    }

    public function getEsPropioSite()
    {
        $this->__load();
        return parent::getEsPropioSite();
    }

    public function setEsPropioEmpresa($esPropioEmpresa)
    {
        $this->__load();
        return parent::setEsPropioEmpresa($esPropioEmpresa);
    }

    public function getEsPropioEmpresa()
    {
        $this->__load();
        return parent::getEsPropioEmpresa();
    }

    public function setEsPropioProducto($esPropioProducto)
    {
        $this->__load();
        return parent::setEsPropioProducto($esPropioProducto);
    }

    public function getEsPropioProducto()
    {
        $this->__load();
        return parent::getEsPropioProducto();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'fecha', 'esProveedor', 'soyProveedor', 'esProveedorProducto', 'esCliente', 'soyCliente', 'esClienteProducto', 'esPropioSite', 'esPropioEmpresa', 'esPropioProducto', 'esPrivada', 'entidad', 'formulariodefinicion', 'entidadesCompartidas');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}