<?php

namespace Proxies\__CG__\Xtending\EntityBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class VerificacionEfectiva extends \Xtending\EntityBundle\Entity\VerificacionEfectiva implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setSupervisor($supervisor)
    {
        $this->__load();
        return parent::setSupervisor($supervisor);
    }

    public function getSupervisor()
    {
        $this->__load();
        return parent::getSupervisor();
    }

    public function setAuditor($auditor)
    {
        $this->__load();
        return parent::setAuditor($auditor);
    }

    public function getAuditor()
    {
        $this->__load();
        return parent::getAuditor();
    }

    public function setFecha($fecha)
    {
        $this->__load();
        return parent::setFecha($fecha);
    }

    public function getFecha()
    {
        $this->__load();
        return parent::getFecha();
    }

    public function setAutor(\Xtending\EntityBundle\Entity\Contactos $autor)
    {
        $this->__load();
        return parent::setAutor($autor);
    }

    public function getAutor()
    {
        $this->__load();
        return parent::getAutor();
    }

    public function getAccionesCorrectivas()
    {
        $this->__load();
        return parent::getAccionesCorrectivas();
    }

    public function addAccionCorrectiva($accionCorrectiva)
    {
        $this->__load();
        return parent::addAccionCorrectiva($accionCorrectiva);
    }

    public function setAccionCorrectiva($accionCorrectiva)
    {
        $this->__load();
        return parent::setAccionCorrectiva($accionCorrectiva);
    }

    public function removeAccionesCorrectiva($accionCorrectiva)
    {
        $this->__load();
        return parent::removeAccionesCorrectiva($accionCorrectiva);
    }

    public function setEstadoSupervisor($estado)
    {
        $this->__load();
        return parent::setEstadoSupervisor($estado);
    }

    public function getEstadoSupervisor()
    {
        $this->__load();
        return parent::getEstadoSupervisor();
    }

    public function getEstadoNombre()
    {
        $this->__load();
        return parent::getEstadoNombre();
    }

    public function getEstadoNombreAuditor()
    {
        $this->__load();
        return parent::getEstadoNombreAuditor();
    }

    public function getEstadoString()
    {
        $this->__load();
        return parent::getEstadoString();
    }

    public function setEstadoAuditor($estado)
    {
        $this->__load();
        return parent::setEstadoAuditor($estado);
    }

    public function getEstadoAuditor()
    {
        $this->__load();
        return parent::getEstadoAuditor();
    }

    public function setEstado($estado)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'supervisor', 'auditor', 'fecha', 'estadoSupervisor', 'estadoAuditor', 'estado', 'autor', 'accionCorrectiva');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}