<?php

namespace Proxies\__CG__\Xtending\EntityBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Planificacion extends \Xtending\EntityBundle\Entity\Planificacion implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setFechaDesde($fecha)
    {
        $this->__load();
        return parent::setFechaDesde($fecha);
    }

    public function getFechaDesde()
    {
        $this->__load();
        return parent::getFechaDesde();
    }

    public function setFechaHasta($fecha)
    {
        $this->__load();
        return parent::setFechaHasta($fecha);
    }

    public function getFechaHasta()
    {
        $this->__load();
        return parent::getFechaHasta();
    }

    public function setFechaCreacion($fecha)
    {
        $this->__load();
        return parent::setFechaCreacion($fecha);
    }

    public function getFechaCreacion()
    {
        $this->__load();
        return parent::getFechaCreacion();
    }

    public function setProceso($formulariosDefiniciones)
    {
        $this->__load();
        return parent::setProceso($formulariosDefiniciones);
    }

    public function getProceso()
    {
        $this->__load();
        return parent::getProceso();
    }

    public function setEstado($estado)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }

    public function getRegistros()
    {
        $this->__load();
        return parent::getRegistros();
    }

    public function addRegistros($registro)
    {
        $this->__load();
        return parent::addRegistros($registro);
    }

    public function removeRegistros($registro)
    {
        $this->__load();
        return parent::removeRegistros($registro);
    }

    public function setAutor($contacto)
    {
        $this->__load();
        return parent::setAutor($contacto);
    }

    public function getAutor()
    {
        $this->__load();
        return parent::getAutor();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'estado', 'fechaDesde', 'fechaHasta', 'fechaCreacion', 'proceso', 'autor', 'registros');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}