<?php

namespace Proxies\__CG__\Xtending\EntityBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CodigoFD extends \Xtending\EntityBundle\Entity\CodigoFD implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setFormularioDefinicion(\Xtending\EntityBundle\Entity\FormulariosDefiniciones $formulario)
    {
        $this->__load();
        return parent::setFormularioDefinicion($formulario);
    }

    public function getFormularioDefinicion()
    {
        $this->__load();
        return parent::getFormularioDefinicion();
    }

    public function setTipoA($tipo)
    {
        $this->__load();
        return parent::setTipoA($tipo);
    }

    public function getTipoA()
    {
        $this->__load();
        return parent::getTipoA();
    }

    public function setCaracterA($caracter)
    {
        $this->__load();
        return parent::setCaracterA($caracter);
    }

    public function getCaracterA()
    {
        $this->__load();
        return parent::getCaracterA();
    }

    public function setTipoB($tipo)
    {
        $this->__load();
        return parent::setTipoB($tipo);
    }

    public function getTipoB()
    {
        $this->__load();
        return parent::getTipoB();
    }

    public function setCaracterB($caracter)
    {
        $this->__load();
        return parent::setCaracterB($caracter);
    }

    public function getCaracterB()
    {
        $this->__load();
        return parent::getCaracterB();
    }

    public function setTipoC($tipo)
    {
        $this->__load();
        return parent::setTipoC($tipo);
    }

    public function getTipoC()
    {
        $this->__load();
        return parent::getTipoC();
    }

    public function setCaracterC($caracter)
    {
        $this->__load();
        return parent::setCaracterC($caracter);
    }

    public function getCaracterC()
    {
        $this->__load();
        return parent::getCaracterC();
    }

    public function setTipoD($tipo)
    {
        $this->__load();
        return parent::setTipoD($tipo);
    }

    public function getTipoD()
    {
        $this->__load();
        return parent::getTipoD();
    }

    public function setCaracterD($caracter)
    {
        $this->__load();
        return parent::setCaracterD($caracter);
    }

    public function getCaracterD()
    {
        $this->__load();
        return parent::getCaracterD();
    }

    public function setTipoE($tipo)
    {
        $this->__load();
        return parent::setTipoE($tipo);
    }

    public function getTipoE()
    {
        $this->__load();
        return parent::getTipoE();
    }

    public function setCaracterE($caracter)
    {
        $this->__load();
        return parent::setCaracterE($caracter);
    }

    public function getCaracterE()
    {
        $this->__load();
        return parent::getCaracterE();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'tipoA', 'caracterA', 'tipoB', 'caracterB', 'tipoC', 'caracterC', 'tipoD', 'caracterD', 'tipoE', 'caracterE', 'formularioDefinicion');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}