<?php

namespace Proxies\__CG__\Xtending\EntityBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EstadoFormularioValor extends \Xtending\EntityBundle\Entity\EstadoFormularioValor implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getTipoParticipante()
    {
        $this->__load();
        return parent::getTipoParticipante();
    }

    public function setTipoParticipante($tipoParticipante)
    {
        $this->__load();
        return parent::setTipoParticipante($tipoParticipante);
    }

    public function getContacto()
    {
        $this->__load();
        return parent::getContacto();
    }

    public function setContacto($contacto)
    {
        $this->__load();
        return parent::setContacto($contacto);
    }

    public function getEstadoFormulario()
    {
        $this->__load();
        return parent::getEstadoFormulario();
    }

    public function setEstadoFormulario($estadoFormulario)
    {
        $this->__load();
        return parent::setEstadoFormulario($estadoFormulario);
    }

    public function getFormularioResultado()
    {
        $this->__load();
        return parent::getFormularioResultado();
    }

    public function setFormularioResultado($formularioResultado)
    {
        $this->__load();
        return parent::setFormularioResultado($formularioResultado);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }

    public function setEstado($estado)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function addFormularioResultado(\Xtending\EntityBundle\Entity\FormulariosResultados $formularioResultado = NULL)
    {
        $this->__load();
        return parent::addFormularioResultado($formularioResultado);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'estado', 'tipoParticipante', 'contacto', 'estadoFormulario', 'formularioResultado');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}