<?php

namespace Proxies\__CG__\Xtending\EntityBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class AccionEjecucion extends \Xtending\EntityBundle\Entity\AccionEjecucion implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setDescripcionAccion($descripcionAccion)
    {
        $this->__load();
        return parent::setDescripcionAccion($descripcionAccion);
    }

    public function getDescripcionAccion()
    {
        $this->__load();
        return parent::getDescripcionAccion();
    }

    public function setFechaAccion($fechaAccion)
    {
        $this->__load();
        return parent::setFechaAccion($fechaAccion);
    }

    public function getFechaAccion()
    {
        $this->__load();
        return parent::getFechaAccion();
    }

    public function setResponsableTxt($responsable)
    {
        $this->__load();
        return parent::setResponsableTxt($responsable);
    }

    public function getResponsableTxt()
    {
        $this->__load();
        return parent::getResponsableTxt();
    }

    public function setResponsable($responsable)
    {
        $this->__load();
        return parent::setResponsable($responsable);
    }

    public function getResponsable()
    {
        $this->__load();
        return parent::getResponsable();
    }

    public function setDescripcionEjecucion($descripcionEjecucion)
    {
        $this->__load();
        return parent::setDescripcionEjecucion($descripcionEjecucion);
    }

    public function getDescripcionEjecucion()
    {
        $this->__load();
        return parent::getDescripcionEjecucion();
    }

    public function setArchivoEjecucion($archivoEjecucion)
    {
        $this->__load();
        return parent::setArchivoEjecucion($archivoEjecucion);
    }

    public function getArchivoEjecucion()
    {
        $this->__load();
        return parent::getArchivoEjecucion();
    }

    public function setFechaEjecucion($fechaEjecucion)
    {
        $this->__load();
        return parent::setFechaEjecucion($fechaEjecucion);
    }

    public function getFechaEjecucion()
    {
        $this->__load();
        return parent::getFechaEjecucion();
    }

    public function setEjecutor($ejecutor)
    {
        $this->__load();
        return parent::setEjecutor($ejecutor);
    }

    public function getEjecutor()
    {
        $this->__load();
        return parent::getEjecutor();
    }

    public function getAccionesCorrectivas()
    {
        $this->__load();
        return parent::getAccionesCorrectivas();
    }

    public function addAccionesCorrectiva($accionCorrectiva)
    {
        $this->__load();
        return parent::addAccionesCorrectiva($accionCorrectiva);
    }

    public function removeAccionesCorrectiva($accionCorrectiva)
    {
        $this->__load();
        return parent::removeAccionesCorrectiva($accionCorrectiva);
    }

    public function getFile()
    {
        $this->__load();
        return parent::getFile();
    }

    public function getAbsolutePath()
    {
        $this->__load();
        return parent::getAbsolutePath();
    }

    public function getWebPath()
    {
        $this->__load();
        return parent::getWebPath();
    }

    public function setFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file = NULL)
    {
        $this->__load();
        return parent::setFile($file);
    }

    public function upload()
    {
        $this->__load();
        return parent::upload();
    }

    public function removeUpload()
    {
        $this->__load();
        return parent::removeUpload();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'descripcionAccion', 'fechaEjecucion', 'descripcionEjecucion', 'archivoEjecucion', 'responsableTxt', 'ejecutor', 'fechaAccion', 'responsable', 'accionCorrectiva');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}