<?php

namespace Proxies\__CG__\Xtending\EntityBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class AlertaRegistro extends \Xtending\EntityBundle\Entity\AlertaRegistro implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setEstado($estado = 1)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }

    public function setUltimaRepeticion($ultimaRepeticion = NULL)
    {
        $this->__load();
        return parent::setUltimaRepeticion($ultimaRepeticion);
    }

    public function getUltimaRepeticion()
    {
        $this->__load();
        return parent::getUltimaRepeticion();
    }

    public function setRegistro($registro)
    {
        $this->__load();
        return parent::setRegistro($registro);
    }

    public function getRegistro()
    {
        $this->__load();
        return parent::getRegistro();
    }

    public function setAlerta($alerta)
    {
        $this->__load();
        return parent::setAlerta($alerta);
    }

    public function getAlerta()
    {
        $this->__load();
        return parent::getAlerta();
    }

    public function setRepeticiones($repeticiones = NULL)
    {
        $this->__load();
        return parent::setRepeticiones($repeticiones);
    }

    public function getRepeticiones()
    {
        $this->__load();
        return parent::getRepeticiones();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'estado', 'repeticiones', 'ultimaRepeticion', 'registro', 'alerta');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}