<?php

namespace Proxies\__CG__\Xtending\EntityBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class AsignacionIndividual extends \Xtending\EntityBundle\Entity\AsignacionIndividual implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setEntidad(\Xtending\EntityBundle\Entity\Entidades $entidad = NULL)
    {
        $this->__load();
        return parent::setEntidad($entidad);
    }

    public function getEntidad()
    {
        $this->__load();
        return parent::getEntidad();
    }

    public function setAsignacion(\Xtending\EntityBundle\Entity\EntidadFormularios $asignacion = NULL)
    {
        $this->__load();
        return parent::setAsignacion($asignacion);
    }

    public function getAsignacion()
    {
        $this->__load();
        return parent::getAsignacion();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function setExterno($externo)
    {
        $this->__load();
        return parent::setExterno($externo);
    }

    public function getExterno()
    {
        $this->__load();
        return parent::getExterno();
    }

    public function setInterno($interno)
    {
        $this->__load();
        return parent::setInterno($interno);
    }

    public function getInterno()
    {
        $this->__load();
        return parent::getInterno();
    }

    public function setCompartido($compartido)
    {
        $this->__load();
        return parent::setCompartido($compartido);
    }

    public function getCompartido()
    {
        $this->__load();
        return parent::getCompartido();
    }

    public function setHabilitado($valor)
    {
        $this->__load();
        return parent::setHabilitado($valor);
    }

    public function getHabilitado()
    {
        $this->__load();
        return parent::getHabilitado();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'externo', 'compartido', 'habilitado', 'interno', 'entidad', 'asignacion');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}