<?php

namespace Proxies\__CG__\Xtending\EntityBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CriterioDefinicion extends \Xtending\EntityBundle\Entity\CriterioDefinicion implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getEmpresas()
    {
        $this->__load();
        return parent::getEmpresas();
    }

    public function setEmpresas($empresas)
    {
        $this->__load();
        return parent::setEmpresas($empresas);
    }

    public function setCaratula($caratula)
    {
        $this->__load();
        return parent::setCaratula($caratula);
    }

    public function getCaratula()
    {
        $this->__load();
        return parent::getCaratula();
    }

    public function setActivo($activo)
    {
        $this->__load();
        return parent::setActivo($activo);
    }

    public function getActivo()
    {
        $this->__load();
        return parent::getActivo();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setEsProveedorSite($esProveedorSite)
    {
        $this->__load();
        return parent::setEsProveedorSite($esProveedorSite);
    }

    public function getEsProveedorSite()
    {
        $this->__load();
        return parent::getEsProveedorSite();
    }

    public function setEsProveedorEmpresa($esProveedorEmpresa)
    {
        $this->__load();
        return parent::setEsProveedorEmpresa($esProveedorEmpresa);
    }

    public function getEsProveedorEmpresa()
    {
        $this->__load();
        return parent::getEsProveedorEmpresa();
    }

    public function setEsProveedorProducto($esProveedorProducto)
    {
        $this->__load();
        return parent::setEsProveedorProducto($esProveedorProducto);
    }

    public function getEsProveedorProducto()
    {
        $this->__load();
        return parent::getEsProveedorProducto();
    }

    public function setEsClienteSite($esClienteSite)
    {
        $this->__load();
        return parent::setEsClienteSite($esClienteSite);
    }

    public function getEsClienteSite()
    {
        $this->__load();
        return parent::getEsClienteSite();
    }

    public function setEsClienteEmpresa($esClienteEmpresa)
    {
        $this->__load();
        return parent::setEsClienteEmpresa($esClienteEmpresa);
    }

    public function getEsClienteEmpresa()
    {
        $this->__load();
        return parent::getEsClienteEmpresa();
    }

    public function setEsClienteProducto($esClienteProducto)
    {
        $this->__load();
        return parent::setEsClienteProducto($esClienteProducto);
    }

    public function getEsClienteProducto()
    {
        $this->__load();
        return parent::getEsClienteProducto();
    }

    public function setEsPropioSite($esPropioSite)
    {
        $this->__load();
        return parent::setEsPropioSite($esPropioSite);
    }

    public function getEsPropioSite()
    {
        $this->__load();
        return parent::getEsPropioSite();
    }

    public function setEsPropioEmpresa($esPropioEmpresa)
    {
        $this->__load();
        return parent::setEsPropioEmpresa($esPropioEmpresa);
    }

    public function getEsPropioEmpresa()
    {
        $this->__load();
        return parent::getEsPropioEmpresa();
    }

    public function setEsPropioProducto($esPropioProducto)
    {
        $this->__load();
        return parent::setEsPropioProducto($esPropioProducto);
    }

    public function getEsPropioProducto()
    {
        $this->__load();
        return parent::getEsPropioProducto();
    }

    public function getEsProveedorContacto()
    {
        $this->__load();
        return parent::getEsProveedorContacto();
    }

    public function setEsProveedorContacto($esProveedorContacto)
    {
        $this->__load();
        return parent::setEsProveedorContacto($esProveedorContacto);
    }

    public function getEsClienteContacto()
    {
        $this->__load();
        return parent::getEsClienteContacto();
    }

    public function setEsClienteContacto($esClienteContacto)
    {
        $this->__load();
        return parent::setEsClienteContacto($esClienteContacto);
    }

    public function getEsPropioContacto()
    {
        $this->__load();
        return parent::getEsPropioContacto();
    }

    public function setEsPropioContacto($esPropioContacto)
    {
        $this->__load();
        return parent::setEsPropioContacto($esPropioContacto);
    }

    public function getLabelsCaratula()
    {
        $this->__load();
        return parent::getLabelsCaratula();
    }

    public function addLabelsCaratulon($label)
    {
        $this->__load();
        return parent::addLabelsCaratulon($label);
    }

    public function removeLabelsCaratulon($label)
    {
        $this->__load();
        return parent::removeLabelsCaratulon($label);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'tipo', 'esProveedorSite', 'esProveedorEmpresa', 'esProveedorProducto', 'esProveedorContacto', 'esClienteSite', 'esClienteEmpresa', 'esClienteProducto', 'esClienteContacto', 'esPropioSite', 'esPropioEmpresa', 'esPropioProducto', 'esPropioContacto', 'activo', 'labelsCaratula', 'empresas');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}