<?php

namespace Proxies\__CG__\Xtending\EntityBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Entidades extends \Xtending\EntityBundle\Entity\Entidades implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getCargos()
    {
        $this->__load();
        return parent::getCargos();
    }

    public function addCargo($cargo)
    {
        $this->__load();
        return parent::addCargo($cargo);
    }

    public function removeCargo($cargo)
    {
        $this->__load();
        return parent::removeCargo($cargo);
    }

    public function getProcesos()
    {
        $this->__load();
        return parent::getProcesos();
    }

    public function addProcesos($procesos)
    {
        $this->__load();
        return parent::addProcesos($procesos);
    }

    public function removeProcesos($procesos)
    {
        $this->__load();
        return parent::removeProcesos($procesos);
    }

    public function getProductos()
    {
        $this->__load();
        return parent::getProductos();
    }

    public function addProductos($productos)
    {
        $this->__load();
        return parent::addProductos($productos);
    }

    public function removeProductos($productos)
    {
        $this->__load();
        return parent::removeProductos($productos);
    }

    public function getContactos()
    {
        $this->__load();
        return parent::getContactos();
    }

    public function addContactos($contactos)
    {
        $this->__load();
        return parent::addContactos($contactos);
    }

    public function removeContactos($contactos)
    {
        $this->__load();
        return parent::removeContactos($contactos);
    }

    public function getClientes()
    {
        $this->__load();
        return parent::getClientes();
    }

    public function addCliente($cliente)
    {
        $this->__load();
        return parent::addCliente($cliente);
    }

    public function removeCliente($cliente)
    {
        $this->__load();
        return parent::removeCliente($cliente);
    }

    public function getProveedores()
    {
        $this->__load();
        return parent::getProveedores();
    }

    public function addProveedor($proveedor)
    {
        $this->__load();
        return parent::addProveedor($proveedor);
    }

    public function removeProveedor($proveedor)
    {
        $this->__load();
        return parent::removeProveedor($proveedor);
    }

    public function getSites()
    {
        $this->__load();
        return parent::getSites();
    }

    public function addSite($site)
    {
        $this->__load();
        return parent::addSite($site);
    }

    public function removeSite($site)
    {
        $this->__load();
        return parent::removeSite($site);
    }

    public function setEntidades($entidades)
    {
        $this->__load();
        return parent::setEntidades($entidades);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCriteriosDefinicion($criteriosDefinicion)
    {
        $this->__load();
        return parent::setCriteriosDefinicion($criteriosDefinicion);
    }

    public function getCriteriosDefinicion()
    {
        $this->__load();
        return parent::getCriteriosDefinicion();
    }

    public function addCriteriosDefinicion($criteriosDefinicion)
    {
        $this->__load();
        return parent::addCriteriosDefinicion($criteriosDefinicion);
    }

    public function removeCriteriosDefinicion($criteriosDefinicion)
    {
        $this->__load();
        return parent::removeCriteriosDefinicion($criteriosDefinicion);
    }

    public function setCorporacion($corporacion)
    {
        $this->__load();
        return parent::setCorporacion($corporacion);
    }

    public function getCorporacion()
    {
        $this->__load();
        return parent::getCorporacion();
    }

    public function addCorporacion($corporacion)
    {
        $this->__load();
        return parent::addCorporacion($corporacion);
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setRazonsocial($razonsocial)
    {
        $this->__load();
        return parent::setRazonsocial($razonsocial);
    }

    public function getRazonsocial()
    {
        $this->__load();
        return parent::getRazonsocial();
    }

    public function setDescripcionempresa($descripcionempresa)
    {
        $this->__load();
        return parent::setDescripcionempresa($descripcionempresa);
    }

    public function getDescripcionempresa()
    {
        $this->__load();
        return parent::getDescripcionempresa();
    }

    public function setDescripcionproductos($descripcionproductos)
    {
        $this->__load();
        return parent::setDescripcionproductos($descripcionproductos);
    }

    public function getDescripcionproductos()
    {
        $this->__load();
        return parent::getDescripcionproductos();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setIdImpuestos($idImpuestos)
    {
        $this->__load();
        return parent::setIdImpuestos($idImpuestos);
    }

    public function getIdImpuestos()
    {
        $this->__load();
        return parent::getIdImpuestos();
    }

    public function setEmailalternativo($emailalternativo)
    {
        $this->__load();
        return parent::setEmailalternativo($emailalternativo);
    }

    public function getEmailalternativo()
    {
        $this->__load();
        return parent::getEmailalternativo();
    }

    public function setPais($pais)
    {
        $this->__load();
        return parent::setPais($pais);
    }

    public function getPais()
    {
        $this->__load();
        return parent::getPais();
    }

    public function setCiudad($ciudad)
    {
        $this->__load();
        return parent::setCiudad($ciudad);
    }

    public function getCiudad()
    {
        $this->__load();
        return parent::getCiudad();
    }

    public function setEstado($estado)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }

    public function setDomicilio($domicilio)
    {
        $this->__load();
        return parent::setDomicilio($domicilio);
    }

    public function getDomicilio()
    {
        $this->__load();
        return parent::getDomicilio();
    }

    public function setTelefonos($telefonos)
    {
        $this->__load();
        return parent::setTelefonos($telefonos);
    }

    public function getTelefonos()
    {
        $this->__load();
        return parent::getTelefonos();
    }

    public function setCodpostal($codpostal)
    {
        $this->__load();
        return parent::setCodpostal($codpostal);
    }

    public function getCodpostal()
    {
        $this->__load();
        return parent::getCodpostal();
    }

    public function setUrl($url)
    {
        $this->__load();
        return parent::setUrl($url);
    }

    public function getUrl()
    {
        $this->__load();
        return parent::getUrl();
    }

    public function setLogo($logo)
    {
        $this->__load();
        return parent::setLogo($logo);
    }

    public function getLogo()
    {
        $this->__load();
        return parent::getLogo();
    }

    public function setFechaalta($fechaalta)
    {
        $this->__load();
        return parent::setFechaalta($fechaalta);
    }

    public function getFechaalta()
    {
        $this->__load();
        return parent::getFechaalta();
    }

    public function setFechabaja($fechabaja)
    {
        $this->__load();
        return parent::setFechabaja($fechabaja);
    }

    public function getFechabaja()
    {
        $this->__load();
        return parent::getFechabaja();
    }

    public function setContactobajaId($contactobajaId)
    {
        $this->__load();
        return parent::setContactobajaId($contactobajaId);
    }

    public function getContactobajaId()
    {
        $this->__load();
        return parent::getContactobajaId();
    }

    public function getFile()
    {
        $this->__load();
        return parent::getFile();
    }

    public function getAbsolutePath()
    {
        $this->__load();
        return parent::getAbsolutePath();
    }

    public function getWebPath()
    {
        $this->__load();
        return parent::getWebPath();
    }

    public function setFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file = NULL)
    {
        $this->__load();
        return parent::setFile($file);
    }

    public function upload()
    {
        $this->__load();
        return parent::upload();
    }

    public function removeUpload()
    {
        $this->__load();
        return parent::removeUpload();
    }

    public function getRelacionIds($tipoEmpresa, $corp = NULL)
    {
        $this->__load();
        return parent::getRelacionIds($tipoEmpresa, $corp);
    }

    public function getEmpresasCorporativas($tipoEmpresa)
    {
        $this->__load();
        return parent::getEmpresasCorporativas($tipoEmpresa);
    }

    public function getStringCliente()
    {
        $this->__load();
        return parent::getStringCliente();
    }

    public function getStringProveedor()
    {
        $this->__load();
        return parent::getStringProveedor();
    }

    public function setRegistrada($registrada)
    {
        $this->__load();
        return parent::setRegistrada($registrada);
    }

    public function getRegistrada()
    {
        $this->__load();
        return parent::getRegistrada();
    }

    public function setInvitadaPor($entidad)
    {
        $this->__load();
        return parent::setInvitadaPor($entidad);
    }

    public function getInvitadaPor()
    {
        $this->__load();
        return parent::getInvitadaPor();
    }

    public function getCodigoplanta()
    {
        $this->__load();
        return parent::getCodigoplanta();
    }

    public function getResponsables(\Xtending\EntityBundle\Entity\Sites $site)
    {
        $this->__load();
        return parent::getResponsables($site);
    }

    public function esEditable($usuario)
    {
        $this->__load();
        return parent::esEditable($usuario);
    }

    public function getEntidadId()
    {
        $this->__load();
        return parent::getEntidadId();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'razonsocial', 'descripcionempresa', 'descripcionproductos', 'email', 'idImpuestos', 'emailalternativo', 'ciudad', 'estado', 'domicilio', 'telefonos', 'codpostal', 'url', 'logo', 'fechaalta', 'fechabaja', 'registrada', 'invitadaPor', 'sites', 'contactos', 'productos', 'cargos', 'corporacion', 'pais', 'contactobajaId', 'clientes', 'proveedores', 'criteriosDefinicion', 'procesos');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}