<?php

namespace Proxies\__CG__\Amateur\ObjectBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Friend extends \Amateur\ObjectBundle\Entity\Friend implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function setUser(\Amateur\ObjectBundle\Entity\User $user)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getIsActive()
    {
        $this->__load();
        return parent::getIsActive();
    }

    public function setIsActive($isActive)
    {
        $this->__load();
        return parent::setIsActive($isActive);
    }

    public function getTipeFriend()
    {
        $this->__load();
        return parent::getTipeFriend();
    }

    public function setTipeFriend($tipeFriend)
    {
        $this->__load();
        return parent::setTipeFriend($tipeFriend);
    }

    public function getUserPendingActive()
    {
        $this->__load();
        return parent::getUserPendingActive();
    }

    public function setUserPendingActive($userPendingActive)
    {
        $this->__load();
        return parent::setUserPendingActive($userPendingActive);
    }

    public function getUserFriend()
    {
        $this->__load();
        return parent::getUserFriend();
    }

    public function setUserFriend(\Amateur\ObjectBundle\Entity\User $userFriend)
    {
        $this->__load();
        return parent::setUserFriend($userFriend);
    }

    public function setFollower(\Amateur\ObjectBundle\Entity\User $friend, \Amateur\ObjectBundle\Entity\User $yo)
    {
        $this->__load();
        return parent::setFollower($friend, $yo);
    }

    public function setFriend(\Amateur\ObjectBundle\Entity\User $friend, \Amateur\ObjectBundle\Entity\User $yo)
    {
        $this->__load();
        return parent::setFriend($friend, $yo);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'isActive', 'tipeFriend', 'userPendingActive', 'userFriend', 'user');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}